apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.app.name }}-node-port-service
spec:
  ports:
      # service port in cluster
    - port: 3000
      # port to contact inside container
      targetPort: 3000
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.type }}