apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  # SERVICE_NAME.NAMESPACE.svc.cluster.local:SERVICE_PORT
  MONGO_URL: {{ .Values.mongodb.name }}-cluster-ip-service.{{ .Release.Namespace }}.svc.cluster.local:27017