apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.mongodb.name }}-cluster-ip-service
spec:
  ports:
      # service port in cluster
    - port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: {{ .Values.mongodb.name }}
  type: {{ .Values.mongodb.type }}