apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.mongodb.name }}
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        # by default, the image is pulled from docker hub
        - image: {{ .Values.images.mongoImage }}
          name: {{ .Values.mongodb.name }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.name }}-{{ .Release.Namespace }}-pv-claim