apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_USERNAME: user1
  MONGO_PASSWORD: pass1
  MONGO_DATABASE: pois